-- STORE PROCEDURE
DELIMITER // 
CREATE PROCEDURE FIRST_PROCEDURE(IN P_ID INT, IN P_NAME CHAR(100), IN P_EMAIL CHAR(100))
BEGIN
	insert INTO customers
    VALUES
    (P_ID, P_NAME, P_EMAIL);
END //

DELIMITER ;

call ecom.FIRST_PROCEDURE(10, 'BLABLA', 'SHFGSD');

