-- WINDOW FUNCTIONS

SELECT * FROM dim_product;

SELECT
	AVG(UNIT_PRICE)
FROM
	dim_product;
 -- IT SHOWS 1 ROW ABOUT AVG UNIT PRICE
 
 -- INSERT 1 MORE COLLUMN
 -- LEVEL 1
 SELECT
	*,
	SUM(UNIT_PRICE) OVER(order by LAUNCH_DATE)
FROM
	dim_product;
-- YOU WILL SEE OVER(ORDER BY) SHOW RUNNING SUM

-- LEVEL 2
-- FRAMES
-- ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW = FROM FIRST ROW TO CURRENT ROW 
-- OVER(ORDER BY) DEFAULT TO UNBOUNDED PRECEDING AND CURRENT ROW
select
	*,
    SUM(unit_price) OVER(ORDER BY LAUNCH_DATE ROWS between unbounded preceding AND current row)
FROM
	DIM_PRODUCT;
    

select
	*,
    SUM(unit_price) OVER(ORDER BY LAUNCH_DATE ROWS between unbounded preceding AND unbounded following)
FROM
	DIM_PRODUCT;
    
    
-- RANKING
-- RANK COUNT THE RECORD 1 - 1 - 3
-- DENSE_RANK NOT COUNT THE RECORD 1 - 1 - 2

-- LEVEL 1
SELECT 
	UNIT_PRICE, 
    ROW_NUMBER() OVER(ORDER BY UNIT_PRICE) AS 'ROW_NUMBER',
    RANK() OVER(ORDER BY UNIT_PRICE) AS 'RANK',
    DENSE_RANK() OVER(ORDER BY UNIT_PRICE) AS 'DENSE_RANK'
FROM DIM_PRODUCT;

-- ROW 455


-- LEVEL 2
-- PARTITION GROUP CATEGORY WITH PARTITION COMMAND
SELECT 
	UNIT_PRICE, 
    CATEGORY,
    ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE) AS 'ROW_NUMBER',
    RANK() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE) AS 'RANK',
    DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE) AS 'DENSE_RANK'
FROM DIM_PRODUCT;



-- SUBQUERY
-- CHAP 9


