-- REAL TIME SCENARIOS

-- SCENARIO 1 (FINDING THE nth VALUE)
SELECT
	SUBQUERY.*
FROM
(
SELECT 
	*,
	DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY UNIT_PRICE DESC) AS RANKING
FROM 
	dim_product
) SUBQUERY
WHERE
	RANKING = 5
ORDER BY
	UNIT_PRICE DESC;
    
-- SCENARIO 2 (REMOVING DUPLICATES)
INSERT INTO customers
VALUES
(301,'LAMBA','CC'),
(101,'LOVE','AA');

SELECT * FROM CUSTOMERS;

SELECT
	SUBQUERY.*
FROM
(
SELECT 
	*,
    ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS DEDUP
FROM
	CUSTOMERS
) SUBQUERY
WHERE
	DEDUP = 1;


-- SCENARIO 3 (LAG & LEAD)
CREATE TABLE WEATHER
(
	ID int,
    TEMPER FLOAT
);
INSERT INTO WEATHER
VALUES
(1,10),
(2,12),
(3,9),
(4,15),
(5,20),
(6,15),
(7,12);

SELECT * FROM weather;

SELECT 
	*,
    LAG(TEMPER,1,0) OVER(ORDER BY ID ASC) AS PREV_DAY_TEMPER,
    LEAD(TEMPER,2,0) OVER(ORDER BY ID ASC) AS NEXT_2DAY_TEMPER,
	LEAD(TEMPER,1,0) OVER(ORDER BY ID ASC) AS NEXT_DAY_TEMPER
FROM 
	WEATHER
